project:
  type: website
  output-dir: docs

website:
  title: "Julia Lee"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
                                                                  
editor: visual

